// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.grpcTrainbooking.proto;

public interface GetUsersBySectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ticket_service.GetUsersBySectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string section = 1;</code>
   */
  java.lang.String getSection();
  /**
   * <code>string section = 1;</code>
   */
  com.google.protobuf.ByteString
      getSectionBytes();
}
