// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.grpcTrainbooking.proto;

/**
 * Protobuf type {@code ticket_service.GetUsersBySectionResponse}
 */
public  final class GetUsersBySectionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ticket_service.GetUsersBySectionResponse)
    GetUsersBySectionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetUsersBySectionResponse.newBuilder() to construct.
  private GetUsersBySectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetUsersBySectionResponse() {
    userInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetUsersBySectionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              userInfo_ = new java.util.ArrayList<com.grpcTrainbooking.proto.Receipt>();
              mutable_bitField0_ |= 0x00000001;
            }
            userInfo_.add(
                input.readMessage(com.grpcTrainbooking.proto.Receipt.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        userInfo_ = java.util.Collections.unmodifiableList(userInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpcTrainbooking.proto.Train.internal_static_ticket_service_GetUsersBySectionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpcTrainbooking.proto.Train.internal_static_ticket_service_GetUsersBySectionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpcTrainbooking.proto.GetUsersBySectionResponse.class, com.grpcTrainbooking.proto.GetUsersBySectionResponse.Builder.class);
  }

  public static final int USER_INFO_FIELD_NUMBER = 1;
  private java.util.List<com.grpcTrainbooking.proto.Receipt> userInfo_;
  /**
   * <code>repeated .ticket_service.Receipt user_info = 1;</code>
   */
  public java.util.List<com.grpcTrainbooking.proto.Receipt> getUserInfoList() {
    return userInfo_;
  }
  /**
   * <code>repeated .ticket_service.Receipt user_info = 1;</code>
   */
  public java.util.List<? extends com.grpcTrainbooking.proto.ReceiptOrBuilder> 
      getUserInfoOrBuilderList() {
    return userInfo_;
  }
  /**
   * <code>repeated .ticket_service.Receipt user_info = 1;</code>
   */
  public int getUserInfoCount() {
    return userInfo_.size();
  }
  /**
   * <code>repeated .ticket_service.Receipt user_info = 1;</code>
   */
  public com.grpcTrainbooking.proto.Receipt getUserInfo(int index) {
    return userInfo_.get(index);
  }
  /**
   * <code>repeated .ticket_service.Receipt user_info = 1;</code>
   */
  public com.grpcTrainbooking.proto.ReceiptOrBuilder getUserInfoOrBuilder(
      int index) {
    return userInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < userInfo_.size(); i++) {
      output.writeMessage(1, userInfo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < userInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, userInfo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpcTrainbooking.proto.GetUsersBySectionResponse)) {
      return super.equals(obj);
    }
    com.grpcTrainbooking.proto.GetUsersBySectionResponse other = (com.grpcTrainbooking.proto.GetUsersBySectionResponse) obj;

    boolean result = true;
    result = result && getUserInfoList()
        .equals(other.getUserInfoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserInfoCount() > 0) {
      hash = (37 * hash) + USER_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getUserInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpcTrainbooking.proto.GetUsersBySectionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ticket_service.GetUsersBySectionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ticket_service.GetUsersBySectionResponse)
      com.grpcTrainbooking.proto.GetUsersBySectionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcTrainbooking.proto.Train.internal_static_ticket_service_GetUsersBySectionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcTrainbooking.proto.Train.internal_static_ticket_service_GetUsersBySectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcTrainbooking.proto.GetUsersBySectionResponse.class, com.grpcTrainbooking.proto.GetUsersBySectionResponse.Builder.class);
    }

    // Construct using com.grpcTrainbooking.proto.GetUsersBySectionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUserInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userInfoBuilder_ == null) {
        userInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        userInfoBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpcTrainbooking.proto.Train.internal_static_ticket_service_GetUsersBySectionResponse_descriptor;
    }

    @java.lang.Override
    public com.grpcTrainbooking.proto.GetUsersBySectionResponse getDefaultInstanceForType() {
      return com.grpcTrainbooking.proto.GetUsersBySectionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpcTrainbooking.proto.GetUsersBySectionResponse build() {
      com.grpcTrainbooking.proto.GetUsersBySectionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpcTrainbooking.proto.GetUsersBySectionResponse buildPartial() {
      com.grpcTrainbooking.proto.GetUsersBySectionResponse result = new com.grpcTrainbooking.proto.GetUsersBySectionResponse(this);
      int from_bitField0_ = bitField0_;
      if (userInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          userInfo_ = java.util.Collections.unmodifiableList(userInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userInfo_ = userInfo_;
      } else {
        result.userInfo_ = userInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpcTrainbooking.proto.GetUsersBySectionResponse) {
        return mergeFrom((com.grpcTrainbooking.proto.GetUsersBySectionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpcTrainbooking.proto.GetUsersBySectionResponse other) {
      if (other == com.grpcTrainbooking.proto.GetUsersBySectionResponse.getDefaultInstance()) return this;
      if (userInfoBuilder_ == null) {
        if (!other.userInfo_.isEmpty()) {
          if (userInfo_.isEmpty()) {
            userInfo_ = other.userInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserInfoIsMutable();
            userInfo_.addAll(other.userInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.userInfo_.isEmpty()) {
          if (userInfoBuilder_.isEmpty()) {
            userInfoBuilder_.dispose();
            userInfoBuilder_ = null;
            userInfo_ = other.userInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            userInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUserInfoFieldBuilder() : null;
          } else {
            userInfoBuilder_.addAllMessages(other.userInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpcTrainbooking.proto.GetUsersBySectionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpcTrainbooking.proto.GetUsersBySectionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.grpcTrainbooking.proto.Receipt> userInfo_ =
      java.util.Collections.emptyList();
    private void ensureUserInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        userInfo_ = new java.util.ArrayList<com.grpcTrainbooking.proto.Receipt>(userInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpcTrainbooking.proto.Receipt, com.grpcTrainbooking.proto.Receipt.Builder, com.grpcTrainbooking.proto.ReceiptOrBuilder> userInfoBuilder_;

    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public java.util.List<com.grpcTrainbooking.proto.Receipt> getUserInfoList() {
      if (userInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userInfo_);
      } else {
        return userInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public int getUserInfoCount() {
      if (userInfoBuilder_ == null) {
        return userInfo_.size();
      } else {
        return userInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public com.grpcTrainbooking.proto.Receipt getUserInfo(int index) {
      if (userInfoBuilder_ == null) {
        return userInfo_.get(index);
      } else {
        return userInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public Builder setUserInfo(
        int index, com.grpcTrainbooking.proto.Receipt value) {
      if (userInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserInfoIsMutable();
        userInfo_.set(index, value);
        onChanged();
      } else {
        userInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public Builder setUserInfo(
        int index, com.grpcTrainbooking.proto.Receipt.Builder builderForValue) {
      if (userInfoBuilder_ == null) {
        ensureUserInfoIsMutable();
        userInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        userInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public Builder addUserInfo(com.grpcTrainbooking.proto.Receipt value) {
      if (userInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserInfoIsMutable();
        userInfo_.add(value);
        onChanged();
      } else {
        userInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public Builder addUserInfo(
        int index, com.grpcTrainbooking.proto.Receipt value) {
      if (userInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserInfoIsMutable();
        userInfo_.add(index, value);
        onChanged();
      } else {
        userInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public Builder addUserInfo(
        com.grpcTrainbooking.proto.Receipt.Builder builderForValue) {
      if (userInfoBuilder_ == null) {
        ensureUserInfoIsMutable();
        userInfo_.add(builderForValue.build());
        onChanged();
      } else {
        userInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public Builder addUserInfo(
        int index, com.grpcTrainbooking.proto.Receipt.Builder builderForValue) {
      if (userInfoBuilder_ == null) {
        ensureUserInfoIsMutable();
        userInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        userInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public Builder addAllUserInfo(
        java.lang.Iterable<? extends com.grpcTrainbooking.proto.Receipt> values) {
      if (userInfoBuilder_ == null) {
        ensureUserInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userInfo_);
        onChanged();
      } else {
        userInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public Builder clearUserInfo() {
      if (userInfoBuilder_ == null) {
        userInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        userInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public Builder removeUserInfo(int index) {
      if (userInfoBuilder_ == null) {
        ensureUserInfoIsMutable();
        userInfo_.remove(index);
        onChanged();
      } else {
        userInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public com.grpcTrainbooking.proto.Receipt.Builder getUserInfoBuilder(
        int index) {
      return getUserInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public com.grpcTrainbooking.proto.ReceiptOrBuilder getUserInfoOrBuilder(
        int index) {
      if (userInfoBuilder_ == null) {
        return userInfo_.get(index);  } else {
        return userInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public java.util.List<? extends com.grpcTrainbooking.proto.ReceiptOrBuilder> 
         getUserInfoOrBuilderList() {
      if (userInfoBuilder_ != null) {
        return userInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userInfo_);
      }
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public com.grpcTrainbooking.proto.Receipt.Builder addUserInfoBuilder() {
      return getUserInfoFieldBuilder().addBuilder(
          com.grpcTrainbooking.proto.Receipt.getDefaultInstance());
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public com.grpcTrainbooking.proto.Receipt.Builder addUserInfoBuilder(
        int index) {
      return getUserInfoFieldBuilder().addBuilder(
          index, com.grpcTrainbooking.proto.Receipt.getDefaultInstance());
    }
    /**
     * <code>repeated .ticket_service.Receipt user_info = 1;</code>
     */
    public java.util.List<com.grpcTrainbooking.proto.Receipt.Builder> 
         getUserInfoBuilderList() {
      return getUserInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpcTrainbooking.proto.Receipt, com.grpcTrainbooking.proto.Receipt.Builder, com.grpcTrainbooking.proto.ReceiptOrBuilder> 
        getUserInfoFieldBuilder() {
      if (userInfoBuilder_ == null) {
        userInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpcTrainbooking.proto.Receipt, com.grpcTrainbooking.proto.Receipt.Builder, com.grpcTrainbooking.proto.ReceiptOrBuilder>(
                userInfo_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      return userInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ticket_service.GetUsersBySectionResponse)
  }

  // @@protoc_insertion_point(class_scope:ticket_service.GetUsersBySectionResponse)
  private static final com.grpcTrainbooking.proto.GetUsersBySectionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpcTrainbooking.proto.GetUsersBySectionResponse();
  }

  public static com.grpcTrainbooking.proto.GetUsersBySectionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUsersBySectionResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetUsersBySectionResponse>() {
    @java.lang.Override
    public GetUsersBySectionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetUsersBySectionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetUsersBySectionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUsersBySectionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpcTrainbooking.proto.GetUsersBySectionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

