// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.grpcTrainbooking.proto;

public interface ModifySeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ticket_service.ModifySeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string new_section = 2;</code>
   */
  java.lang.String getNewSection();
  /**
   * <code>string new_section = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewSectionBytes();

  /**
   * <code>int32 new_seat_number = 3;</code>
   */
  int getNewSeatNumber();
}
