// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.grpcTrainbooking.proto;

public interface ModifySeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ticket_service.ModifySeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string res = 1;</code>
   */
  java.lang.String getRes();
  /**
   * <code>string res = 1;</code>
   */
  com.google.protobuf.ByteString
      getResBytes();
}
