// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.grpcTrainbooking.proto;

public interface PurchaseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ticket_service.PurchaseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from = 1;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string to = 2;</code>
   */
  java.lang.String getTo();
  /**
   * <code>string to = 2;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>.ticket_service.User user = 3;</code>
   */
  boolean hasUser();
  /**
   * <code>.ticket_service.User user = 3;</code>
   */
  com.grpcTrainbooking.proto.User getUser();
  /**
   * <code>.ticket_service.User user = 3;</code>
   */
  com.grpcTrainbooking.proto.UserOrBuilder getUserOrBuilder();

  /**
   * <code>double price_paid = 4;</code>
   */
  double getPricePaid();

  /**
   * <code>string purchase_id = 5;</code>
   */
  java.lang.String getPurchaseId();
  /**
   * <code>string purchase_id = 5;</code>
   */
  com.google.protobuf.ByteString
      getPurchaseIdBytes();
}
