// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.grpcTrainbooking.proto;

public interface ReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ticket_service.Receipt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from = 1;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string to = 2;</code>
   */
  java.lang.String getTo();
  /**
   * <code>string to = 2;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>.ticket_service.User user = 3;</code>
   */
  boolean hasUser();
  /**
   * <code>.ticket_service.User user = 3;</code>
   */
  com.grpcTrainbooking.proto.User getUser();
  /**
   * <code>.ticket_service.User user = 3;</code>
   */
  com.grpcTrainbooking.proto.UserOrBuilder getUserOrBuilder();

  /**
   * <code>.ticket_service.Seat seat = 4;</code>
   */
  boolean hasSeat();
  /**
   * <code>.ticket_service.Seat seat = 4;</code>
   */
  com.grpcTrainbooking.proto.Seat getSeat();
  /**
   * <code>.ticket_service.Seat seat = 4;</code>
   */
  com.grpcTrainbooking.proto.SeatOrBuilder getSeatOrBuilder();

  /**
   * <code>float price_paid = 5;</code>
   */
  float getPricePaid();

  /**
   * <code>string purchase_id = 6;</code>
   */
  java.lang.String getPurchaseId();
  /**
   * <code>string purchase_id = 6;</code>
   */
  com.google.protobuf.ByteString
      getPurchaseIdBytes();
}
