// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.grpcTrainbooking.proto;

public interface SeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ticket_service.Seat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string section = 1;</code>
   */
  java.lang.String getSection();
  /**
   * <code>string section = 1;</code>
   */
  com.google.protobuf.ByteString
      getSectionBytes();

  /**
   * <code>int32 seat_number = 2;</code>
   */
  int getSeatNumber();
}
