// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.grpcTrainbooking.proto;

public interface ShowReceiptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ticket_service.ShowReceiptResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ticket_service.Receipt user_info = 1;</code>
   */
  boolean hasUserInfo();
  /**
   * <code>.ticket_service.Receipt user_info = 1;</code>
   */
  com.grpcTrainbooking.proto.Receipt getUserInfo();
  /**
   * <code>.ticket_service.Receipt user_info = 1;</code>
   */
  com.grpcTrainbooking.proto.ReceiptOrBuilder getUserInfoOrBuilder();
}
